name: CI

on:
  push:
    branches:
      - '*'

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Get an env
        uses: yetanalytics/action-setup-env@v1
      
      - name: Test build
        run: make test-build
      
      - name: Test deploy
        run: make test-deploy
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_DEPLOY_TOKEN }}
